export interface ChatTelemetryRow {
  id?: string                        // generated by DB
  created_at: string                 // ISO timestamp of requestStartedAt
  stream_start_time: string | null
  ttft_ms: number | null
  ttfs_ms: number | null
  ttfa_ms: number | null
  tts_total_ms: number | null
  duration_ms: number | null
  llm_provider: string
  llm_model: string
  tts_provider: string
  tts_voice: string
  tts_mode: string
  session_type: string
  user_id: string
  conversation_id: string
  message_id: string | null
  request_id: string
  token_count: number | null
  sentence_count: number | null
  is_session_start: boolean
  status: 'success' | 'error'
  error_type: string | null
  resilience_attempt: number | null
  resilience_route: string | null
}

interface CollectorInit {
  requestId: string
  requestStartedAt: number           // Date.now() at handler entry
  userId: string
  conversationId: string
  llmProvider: string                // e.g., 'groq'
  llmModel: string                   // e.g., 'openai/gpt-oss-20b'
  ttsProvider: string                // e.g., 'groq'
  ttsVoice: string                   // e.g., 'troy'
  ttsMode: string                    // e.g., 'sentence-batch'
  sessionType: string                // e.g., 'core'
  isSessionStart: boolean
  resilienceAttempt: number | null
  resilienceRoute: string | null
}

export class ChatTelemetryCollector {
  private data: Partial<ChatTelemetryRow>
  private streamStartTime: number | null = null
  private firstTokenMarked = false
  private firstSentenceMarked = false
  private firstAudioMarked = false
  private requestStartedAt: number

  constructor(init: CollectorInit) {
    this.requestStartedAt = init.requestStartedAt
    this.data = {
      created_at: new Date(init.requestStartedAt).toISOString(),
      llm_provider: init.llmProvider,
      llm_model: init.llmModel,
      tts_provider: init.ttsProvider,
      tts_voice: init.ttsVoice,
      tts_mode: init.ttsMode,
      session_type: init.sessionType,
      user_id: init.userId,
      conversation_id: init.conversationId,
      message_id: null,
      request_id: init.requestId,
      is_session_start: init.isSessionStart,
      resilience_attempt: init.resilienceAttempt,
      resilience_route: init.resilienceRoute,
    }
  }

  markStreamStart(): void {
    this.streamStartTime = Date.now()
    this.data.stream_start_time = new Date().toISOString()
  }

  markFirstToken(): void {
    if (this.firstTokenMarked || !this.streamStartTime) return
    this.firstTokenMarked = true
    this.data.ttft_ms = Date.now() - this.streamStartTime
  }

  markFirstSentence(): void {
    if (this.firstSentenceMarked || !this.streamStartTime) return
    this.firstSentenceMarked = true
    this.data.ttfs_ms = Date.now() - this.streamStartTime
  }

  markFirstAudio(): void {
    if (this.firstAudioMarked || !this.streamStartTime) return
    this.firstAudioMarked = true
    this.data.ttfa_ms = Date.now() - this.streamStartTime
  }

  setMessageId(id: string | null): void {
    this.data.message_id = id
  }

  markComplete(metrics: {
    tokenCount: number
    sentenceCount: number
    ttsMode: string
  }): void {
    this.data.status = 'success'
    this.data.duration_ms = Date.now() - this.requestStartedAt
    this.data.token_count = metrics.tokenCount
    this.data.sentence_count = metrics.sentenceCount
    this.data.tts_mode = metrics.ttsMode  // effective mode (may differ from config)
    if (this.streamStartTime) {
      this.data.tts_total_ms = Date.now() - this.streamStartTime
    }
  }

  markError(error: Error): void {
    this.data.status = 'error'
    this.data.duration_ms = Date.now() - this.requestStartedAt
    this.data.error_type = classifyTelemetryError(error)
  }

  writeTo(supabase: any): void {
    const row = { ...this.data } as ChatTelemetryRow
    supabase
      .from('chat_telemetry')
      .insert(row)
      .then(({ error }: { error: any }) => {
        if (error) {
          console.error('[telemetry] Write failed', {
            requestId: row.request_id,
            error: error.message,
          })
        }
      })
      .catch((err: any) => {
        console.error('[telemetry] Write failed', {
          requestId: row.request_id,
          error: err.message,
        })
      })
  }
}

export function classifyTelemetryError(error: Error): string {
  const status = (error as any)?.status
  const msg = error.message?.toLowerCase() || ''

  if (status === 408 || msg.includes('timeout')) return 'LLM_TIMEOUT'
  if (status === 429 || msg.includes('rate limit')) return 'LLM_RATE_LIMIT'
  if (status === 503 || (status && status >= 500)) return 'LLM_PROVIDER_ERROR'
  if (msg.includes('tts') || msg.includes('synthesize')) return 'TTS_PROVIDER_ERROR'
  if (msg.includes('abort') || msg.includes('cancel')) return 'STREAM_INTERRUPTED'
  return 'UNKNOWN_ERROR'
}
